rm -f ~/.config/ros.org/*.ini
touch ~/.config/ros.org/rqt_gui.ini
cat rqt_config.txt >> ~/.config/ros.org/rqt_gui.ini

rqt_plot /sot/ctrl_man/u/data[0] /sot/ctrl_man/u/data[1] /sot/ctrl_man/u/data[2] /sot/ctrl_man/u/data[3] /sot/ctrl_man/u/data[4] /sot/ctrl_man/u/data[5] /sot/ctrl_man/u/data[6] /sot/ctrl_man/u/data[7] /sot/ctrl_man/u/data[8] /sot/ctrl_man/u/data[9] /sot/ctrl_man/u/data[10] /sot/ctrl_man/u/data[11] /sot/ctrl_man/u/data[12] /sot/ctrl_man/u/data[13] /sot/ctrl_man/u/data[14] /sot/ctrl_man/u/data[15] /sot/ctrl_man/u/data[16] /sot/ctrl_man/u/data[17] /sot/ctrl_man/u/data[18] /sot/ctrl_man/u/data[19] /sot/ctrl_man/u/data[20] /sot/ctrl_man/u/data[21] /sot/ctrl_man/u/data[22] /sot/ctrl_man/u/data[23] /sot/ctrl_man/u/data[24] /sot/ctrl_man/u/data[25] /sot/ctrl_man/u/data[26] /sot/ctrl_man/u/data[27] /sot/ctrl_man/u/data[28] /sot/ctrl_man/u/data[29] /sot/ctrl_man/u/data[30] /sot/ctrl_man/u/data[31] /sot/ctrl_man/u/data[32] /sot/ctrl_man/u/data[33] /sot/ctrl_man/u/data[34] /sot/ctrl_man/u/data[35] /sot/ctrl_man/u/data[36] /sot/ctrl_man/u/data[37] &

rqt_plot /sot/ctrl_man/u_safe/data[0] /sot/ctrl_man/u_safe/data[1] /sot/ctrl_man/u_safe/data[2] /sot/ctrl_man/u_safe/data[3] /sot/ctrl_man/u_safe/data[4] /sot/ctrl_man/u_safe/data[5] /sot/ctrl_man/u_safe/data[6] /sot/ctrl_man/u_safe/data[7] /sot/ctrl_man/u_safe/data[8] /sot/ctrl_man/u_safe/data[9] /sot/ctrl_man/u_safe/data[10] /sot/ctrl_man/u_safe/data[11] /sot/ctrl_man/u_safe/data[12] /sot/ctrl_man/u_safe/data[13] /sot/ctrl_man/u_safe/data[14] /sot/ctrl_man/u_safe/data[15] /sot/ctrl_man/u_safe/data[16] /sot/ctrl_man/u_safe/data[17] /sot/ctrl_man/u_safe/data[18] /sot/ctrl_man/u_safe/data[19] /sot/ctrl_man/u_safe/data[20] /sot/ctrl_man/u_safe/data[21] /sot/ctrl_man/u_safe/data[22] /sot/ctrl_man/u_safe/data[23] /sot/ctrl_man/u_safe/data[24] /sot/ctrl_man/u_safe/data[25] /sot/ctrl_man/u_safe/data[26] /sot/ctrl_man/u_safe/data[27] /sot/ctrl_man/u_safe/data[28] /sot/ctrl_man/u_safe/data[29] /sot/ctrl_man/u_safe/data[30] /sot/ctrl_man/u_safe/data[31] /sot/ctrl_man/u_safe/data[32] /sot/ctrl_man/u_safe/data[33] /sot/ctrl_man/u_safe/data[34] /sot/ctrl_man/u_safe/data[35] /sot/ctrl_man/u_safe/data[36] /sot/ctrl_man/u_safe/data[37] &

rqt_plot /sot/ctrl_man/emergencyStop_zmp/data &
